namespace PhaseDiagram.Services.Thermo;

/// <summary>
/// Phase envelope service using CoolProp PR/SRK build_phase_envelope.
/// DEFAULT UNITS: Pressure in psia, Temperature in °F (Field/Oilfield Units)
///
/// Liquid dropout contours are generated by geometric interpolation between
/// the bubble and dew curves.  At each pressure level:
///
///   T(LF, P) = Tdew(P) + LF^α × (Tbubble(P) − Tdew(P))
///
/// where α is a power-law exponent that controls the spacing of contours.
/// α = 0.5 compresses lines toward the dew curve (correct for lean gas);
/// the contours converge naturally to the critical point where Tbub = Tdew.
///
/// This approach:
///   • Makes ZERO CoolProp flash calls for dropout lines
///   • Is guaranteed inside the envelope by construction
///   • Is guaranteed correctly ordered (higher LF → closer to bubble)
///   • Produces perfectly smooth curves (no noise, no wrong roots)
///   • Completes in milliseconds
/// </summary>
public sealed class CoolPropPhaseEnvelopeService
{
    #region DTOs

    public sealed record PhaseEnvelopeRequest(
        string Backend, string[] Components, double[] Z,
        double TminF, double TmaxF, int Points, double[] LiquidLines);

    public sealed record PhaseEnvelopeResult(
        (double T_F, double P_psia)[] Bubble,
        (double T_F, double P_psia)[] Dew,
        Dictionary<double, (double T_F, double P_psia)[]> LiquidLines,
        (double Tcrit_F, double Pcrit_psia)? Critical,
        string Backend, string[] Components, double[] Composition);

    #endregion

    #region Constants

    private const double PA_TO_PSI = 1.0 / 6894.757293168;
    private const double PSI_TO_PA = 6894.757293168;
    private const double F_TO_K_OFFSET = 459.67;
    private const double F_TO_K_SCALE = 5.0 / 9.0;

    /// <summary>Number of pressure levels for dropout contour interpolation.</summary>
    private const int ContourPressureLevels = 200;

    /// <summary>
    /// Power-law exponent for dropout line interpolation.
    /// Controls how contours are spaced between bubble and dew.
    /// α &lt; 1 compresses toward dew (correct for most hydrocarbon mixtures).
    /// α = 1 gives linear spacing.
    /// α &gt; 1 compresses toward bubble.
    /// </summary>
    private const double InterpolationExponent = 0.5;

    /// <summary>
    /// Pressure ceiling for contours, as a fraction of Pcrit.
    /// Contours stop before the critical point since they must
    /// converge there (Tbub = Tdew = Tcrit).
    /// </summary>
    private const double PressureCeilingFraction = 0.995;

    /// <summary>CoolProp C API global handle — serialise all calls.</summary>
    private static readonly SemaphoreSlim _coolPropLock = new(1, 1);

    #endregion

    #region Component Name Mapping

    private static readonly Dictionary<string, string> ComponentMapping =
        new(StringComparer.OrdinalIgnoreCase)
        {
            ["C1"] = "Methane",
            ["Methane"] = "Methane",
            ["C2"] = "Ethane",
            ["Ethane"] = "Ethane",
            ["C3"] = "Propane",
            ["Propane"] = "Propane",
            ["iC4"] = "IsoButane",
            ["i-C4"] = "IsoButane",
            ["Isobutane"] = "IsoButane",
            ["nC4"] = "n-Butane",
            ["n-C4"] = "n-Butane",
            ["Butane"] = "n-Butane",
            ["iC5"] = "Isopentane",
            ["i-C5"] = "Isopentane",
            ["Isopentane"] = "Isopentane",
            ["nC5"] = "n-Pentane",
            ["n-C5"] = "n-Pentane",
            ["Pentane"] = "n-Pentane",
            ["C6"] = "n-Hexane",
            ["nC6"] = "n-Hexane",
            ["Hexane"] = "n-Hexane",
            ["C7"] = "n-Heptane",
            ["nC7"] = "n-Heptane",
            ["Heptane"] = "n-Heptane",
            ["C8"] = "n-Octane",
            ["nC8"] = "n-Octane",
            ["Octane"] = "n-Octane",
            ["C9"] = "n-Nonane",
            ["nC9"] = "n-Nonane",
            ["Nonane"] = "n-Nonane",
            ["C10"] = "n-Decane",
            ["nC10"] = "n-Decane",
            ["Decane"] = "n-Decane",
            ["CO2"] = "CarbonDioxide",
            ["CarbonDioxide"] = "CarbonDioxide",
            ["N2"] = "Nitrogen",
            ["Nitrogen"] = "Nitrogen",
            ["H2S"] = "HydrogenSulfide",
            ["HydrogenSulfide"] = "HydrogenSulfide",
            ["H2O"] = "Water",
            ["Water"] = "Water",
        };

    #endregion

    #region Unit Helpers

    private static double FahrenheitToKelvin(double f) => (f + F_TO_K_OFFSET) * F_TO_K_SCALE;
    private static double KelvinToFahrenheit(double k) => k / F_TO_K_SCALE - F_TO_K_OFFSET;
    private static double PascalToPsia(double pa) => pa * PA_TO_PSI;

    private static (double T_F, double P_psia)[] ToFieldUnits((double T_K, double P_Pa)[] pts)
        => pts.Select(p => (KelvinToFahrenheit(p.T_K), PascalToPsia(p.P_Pa))).ToArray();

    #endregion

    #region Public API

    public PhaseEnvelopeResult GeneratePhaseEnvelope(PhaseEnvelopeRequest request)
    {
        ValidateRequest(request);
        var comps = MapComponentNames(request.Components);
        var z = NormalizeComposition(request.Z);
        double tMinK = FahrenheitToKelvin(request.TminF);
        double tMaxK = FahrenheitToKelvin(request.TmaxF);

        var (bubK, dewK, critK) = TraceEnvelope(comps, z, tMinK, tMaxK, request.Backend);

        if (bubK.Length == 0 && dewK.Length == 0)
            Console.WriteLine($"[PhaseEnvelope] WARNING: No points for {string.Join("+", comps)} / {request.Backend}.");

        var liqLines = GenerateLiquidContours(bubK, dewK, critK, request.LiquidLines);

        return new PhaseEnvelopeResult(
            Bubble: ToFieldUnits(bubK),
            Dew: ToFieldUnits(dewK),
            LiquidLines: liqLines.ToDictionary(kv => kv.Key, kv => ToFieldUnits(kv.Value)),
            Critical: critK.HasValue
                ? (KelvinToFahrenheit(critK.Value.T_K), PascalToPsia(critK.Value.P_Pa))
                : null,
            Backend: request.Backend,
            Components: comps,
            Composition: z);
    }

    public PhaseEnvelopeResult GenerateEnvelopeOilfield(
        string backend, Dictionary<string, double> composition,
        double minTempF = -150, double maxTempF = 350,
        int points = 50, double[]? liquidFractions = null)
    {
        liquidFractions ??= [0.01, 0.05, 0.10, 0.25];
        return GeneratePhaseEnvelope(new PhaseEnvelopeRequest(
            backend, composition.Keys.ToArray(), composition.Values.ToArray(),
            minTempF, maxTempF, points, liquidFractions));
    }

    #endregion

    #region Envelope Tracing

    private static (
        (double T_K, double P_Pa)[] bubble,
        (double T_K, double P_Pa)[] dew,
        (double T_K, double P_Pa)? critical)
        TraceEnvelope(string[] comps, double[] z, double tMinK, double tMaxK, string backend)
    {
        var (bubble, dew, critical) = CoolPropSharpWrapper.BuildPhaseEnvelope(backend, comps, z);

        if (bubble.Length == 0 && dew.Length == 0)
        {
            Console.WriteLine($"[TraceEnvelope] No points returned for backend={backend}.");
            return ([], [], null);
        }

        var bubF = bubble.Where(p => double.IsFinite(p.T_K) && p.T_K >= tMinK && p.T_K <= tMaxK).ToArray();
        var dewF = dew.Where(p => double.IsFinite(p.T_K) && p.T_K >= tMinK && p.T_K <= tMaxK).ToArray();

        Console.WriteLine($"[TraceEnvelope] bubble={bubF.Length}, dew={dewF.Length} pts after filter.");
        return (bubF, dewF, critical);
    }

    #endregion

    #region Liquid Dropout Contours — Geometric Interpolation

    /// <summary>
    /// Generates liquid dropout contours by geometric interpolation between
    /// the bubble and dew curves. No CoolProp flash calls are made.
    ///
    /// At each pressure P where both Tbubble and Tdew can be interpolated:
    ///   T(LF, P) = Tdew(P) + LF^α × (Tbubble(P) − Tdew(P))
    ///
    /// LF = 0 → on the dew curve (0% liquid, all vapor)
    /// LF = 1 → on the bubble curve (100% liquid)
    ///
    /// The power-law exponent α controls spacing:
    ///   α = 0.5 → √LF → lines compressed toward dew (physically reasonable)
    ///   α = 1.0 → linear interpolation
    ///
    /// All contours converge naturally to the critical point where
    /// Tbubble = Tdew, producing the characteristic "fan" shape.
    /// </summary>
    private static Dictionary<double, (double T_K, double P_Pa)[]> GenerateLiquidContours(
        (double T_K, double P_Pa)[] bubble,
        (double T_K, double P_Pa)[] dew,
        (double T_K, double P_Pa)? critical,
        double[] liquidFractions)
    {
        var result = new Dictionary<double, (double T_K, double P_Pa)[]>();

        if (bubble.Length < 2 || dew.Length < 2 || !critical.HasValue || liquidFractions.Length == 0)
            return result;

        double pCritPa = critical.Value.P_Pa;

        // Determine the pressure range where BOTH curves have data.
        double pMinBub = bubble.Min(p => p.P_Pa);
        double pMinDew = dew.Min(p => p.P_Pa);
        double pMaxBub = bubble.Max(p => p.P_Pa);
        double pMaxDew = dew.Max(p => p.P_Pa);

        double pFloor = Math.Max(pMinBub, pMinDew);
        double pCeiling = Math.Min(Math.Min(pMaxBub, pMaxDew), pCritPa * PressureCeilingFraction);

        if (pCeiling <= pFloor)
        {
            Console.WriteLine("[LiquidContours] No overlapping pressure range between bubble and dew.");
            return result;
        }

        // Generate uniform pressure levels.
        var pressures = new double[ContourPressureLevels];
        for (int i = 0; i < ContourPressureLevels; i++)
            pressures[i] = pFloor + (pCeiling - pFloor) * i / (ContourPressureLevels - 1);

        foreach (double lf in liquidFractions)
        {
            if (lf <= 0 || lf >= 1) continue;

            // Power-law weight: how far from dew toward bubble.
            double w = Math.Pow(lf, InterpolationExponent);

            var pts = new List<(double T_K, double P_Pa)>();

            foreach (double pPa in pressures)
            {
                // Get the dew boundary (right/high-T) at this pressure.
                double tDew = InterpolateCurveMaxT(dew, pPa);
                if (tDew <= 0) tDew = InterpolateCurveMinT(dew, pPa);

                // Get the bubble boundary (left/low-T) at this pressure.
                double tBub = InterpolateCurveMinT(bubble, pPa);
                if (tBub <= 0) tBub = InterpolateCurveMaxT(bubble, pPa);

                if (tDew <= 0 || tBub <= 0) continue;

                // For a normal envelope: tBub < tDew in the retrograde region,
                // but tBub > tDew below the cricondentherm. Handle both cases.
                // The interpolation still works: w=0 → dew, w=1 → bubble.
                double tContour = tDew + w * (tBub - tDew);

                if (double.IsFinite(tContour) && tContour > 0)
                    pts.Add((tContour, pPa));
            }

            if (pts.Count >= 3)
            {
                result[lf] = pts.ToArray();
                Console.WriteLine($"[LiquidContours] LF={lf:P0}: {pts.Count} pts (geometric interpolation).");
            }
        }

        return result;
    }

    #endregion

    #region Envelope Curve Interpolation

    /// <summary>
    /// Find the maximum T on a curve at a given pressure.
    /// Scans all segments for intersections and returns the highest T found.
    /// </summary>
    private static double InterpolateCurveMaxT((double T_K, double P_Pa)[] curve, double P)
    {
        if (curve.Length < 2) return 0;
        double maxT = 0;
        bool found = false;

        for (int i = 0; i < curve.Length - 1; i++)
        {
            double p0 = curve[i].P_Pa, p1 = curve[i + 1].P_Pa;
            double pMin = Math.Min(p0, p1), pMax = Math.Max(p0, p1);
            if (P < pMin || P > pMax) continue;
            double denom = p1 - p0;
            if (Math.Abs(denom) < 1e-10) continue;
            double frac = (P - p0) / denom;
            double t = curve[i].T_K + frac * (curve[i + 1].T_K - curve[i].T_K);
            if (t > maxT) { maxT = t; found = true; }
        }
        return found ? maxT : 0;
    }

    /// <summary>
    /// Find the minimum T on a curve at a given pressure.
    /// </summary>
    private static double InterpolateCurveMinT((double T_K, double P_Pa)[] curve, double P)
    {
        if (curve.Length < 2) return 0;
        double minT = double.MaxValue;
        bool found = false;

        for (int i = 0; i < curve.Length - 1; i++)
        {
            double p0 = curve[i].P_Pa, p1 = curve[i + 1].P_Pa;
            double pMin = Math.Min(p0, p1), pMax = Math.Max(p0, p1);
            if (P < pMin || P > pMax) continue;
            double denom = p1 - p0;
            if (Math.Abs(denom) < 1e-10) continue;
            double frac = (P - p0) / denom;
            double t = curve[i].T_K + frac * (curve[i + 1].T_K - curve[i].T_K);
            if (t < minT) { minT = t; found = true; }
        }
        return found ? minT : 0;
    }

    #endregion

    #region Validation & Helpers

    private static void ValidateRequest(PhaseEnvelopeRequest request)
    {
        if (request.Components is null || request.Components.Length == 0)
            throw new ArgumentException("At least one component is required.");
        if (request.Z is null || request.Z.Length != request.Components.Length)
            throw new ArgumentException("Composition array length must match components.");
        if (request.Z.Any(z => z < 0))
            throw new ArgumentException("Negative mole fractions are not allowed.");
        if (request.Z.Sum() <= 0)
            throw new ArgumentException("Total mole fraction must be positive.");
        if (request.TminF >= request.TmaxF)
            throw new ArgumentException("Minimum temperature must be less than maximum.");
        if (request.Points < 10)
            throw new ArgumentException("At least 10 points required.");
        if (!new[] { "PR", "SRK" }.Contains(request.Backend, StringComparer.OrdinalIgnoreCase))
            throw new ArgumentException("Backend must be 'PR' or 'SRK'.");
    }

    private static string[] MapComponentNames(string[] components)
        => components.Select(c =>
            ComponentMapping.TryGetValue(c, out var mapped)
                ? mapped
                : throw new ArgumentException($"Unknown component: '{c}'"))
        .ToArray();

    private static double[] NormalizeComposition(double[] z)
    {
        double sum = z.Sum();
        return Math.Abs(sum - 1.0) < 1e-6 ? z : z.Select(zi => zi / sum).ToArray();
    }

    #endregion
}